### ISSUE TITLE
Upravy textov Zapoj sa

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/slovensko.digital#26]
https://slovensko.digital/zapoj-sa/zacni-programovat

-  zmenit text _Aj preto sme rozbehli ekosystém.slovensko.digital (GovBox, Autoform, DataHub), či projekt volby.digital_ na _Aj preto sme rozbehli ekosystém.slovensko.digital (GovBox, Autoform, DataHub), či projekty [Volby.Digital](https://volby.digital/) a [Návody.Digital](https://navody.digital/)._ 

-  zmenit odkaz na GitHub z ekosystemu na navodove repo https://github.com/slovensko-digital/navody.digital/issues

![targetprocess-screen-capture (4)](https://user-images.githubusercontent.com/45393631/67198013-57b17080-f3fe-11e9-8fc2-96f178b6b4fd.png)

**Comment by HanaBene** [comment]
@smith558 mozes sa na to prosim pozriet? dakujem.

**Comment by smith558** [comment]
**In progress**

**Comment by smith558** [comment]
@HanaBene odkaz na issues ohladne eko chces dat uplne prec?

**Comment by smith558** [comment]
**Done**
